// <auto-generated />
namespace DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migratedatetime2ToDatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migratedatetime2ToDatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201810181924200_migrate-datetime2ToDatetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
