// <auto-generated />
namespace DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DBSETQuestionAnswerAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBSETQuestionAnswerAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201809241236396_DBSET-Question-Answer-Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
