// <auto-generated />
namespace DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class allowhtmltoQuestionText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowhtmltoQuestionText));
        
        string IMigrationMetadata.Id
        {
            get { return "201809241409385_allow-html-to-QuestionText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
